wordchain/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('wordchain_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

wordchain_app/urls.py
from django.urls import path
from . import views

app_name = 'wordchain'

urlpatterns = [
    path('', views.play, name='play'),
    path('account/', views.account, name='account'),
    path('about/', views.about, name='about'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('update_account_details/', views.update_account_details, name='update_account_details'),
    path('stats/', views.stats, name='stats'),
]

wordchain_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Chain(models.Model):
    chain_id = models.AutoField(primary_key=True)
    first_word = models.CharField(max_length=13)
    second_word = models.CharField(max_length=13)
    third_word = models.CharField(max_length=13)
    fourth_word = models.CharField(max_length=13)
    fifth_word = models.CharField(max_length=13)
    sixth_word = models.CharField(max_length=13)


class Score(models.Model):
    score_id = models.AutoField(primary_key=True)
    value = models.IntegerField()


class Results(models.Model):
    score = models.ForeignKey('Score', on_delete=models.CASCADE)
    chain = models.ForeignKey('Chain', on_delete=models.CASCADE)


class Level(models.Model):
    difficulty = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Selects(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    level = models.ForeignKey('Level', on_delete=models.CASCADE)


class Display(models.Model):
    display_id = models.AutoField(primary_key=True)
    visual_mode = models.CharField(max_length=20)
    accessibility = models.CharField(max_length=20)


class SetView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    display = models.ForeignKey('Display', on_delete=models.CASCADE)


class ReceiveScore(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.ForeignKey('Score', on_delete=models.CASCADE)


class IsAssignedTo(models.Model):
    chain = models.ForeignKey('Chain', on_delete=models.CASCADE)
    level = models.ForeignKey('Level', on_delete=models.CASCADE)


class PlayGame(models.Model):
    chain = models.ForeignKey('Chain', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

wordchain_app/forms.py
from django.contrib.auth import forms, models


class UserForm(forms.UserCreationForm):
    class Meta:
        model = models.User
        fields = ('first_name', 'last_name', 'username', 'password1')

wordchain_app/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from django.db.models import Q

from .forms import UserForm
from .models import *
import json


@login_required
def play(request):
    if request.method == 'POST':
        request_data = request.body.decode("utf-8")
        data = json.loads(request_data)
        score = Score.objects.create(value=data['score'])
        ReceiveScore.objects.create(user=request.user, score=score)
        chain = Chain.objects.get(chain_id=data['chain'])
        Results.objects.create(chain=chain, score=score)
        PlayGame.objects.create(chain=chain, user=request.user)

    chain = Chain.objects.order_by('?').first()
    if (Chain.objects.count() <= PlayGame.objects.filter(user_id=request.user.id).count()) or (chain is None):
        return render(request, "wordchain_app/play-no-chains.html", {"style": set_style(request.user)})
    while PlayGame.objects.filter(chain=chain, user_id=request.user.id).exists():
        chain = Chain.objects.order_by('?').first()

    isassignto = IsAssignedTo.objects.get(chain=chain)
    Selects.objects.update_or_create(user=request.user, defaults={"level":isassignto.level})
    level = isassignto.level.difficulty
    context = {
        "level": level,
        "style": set_style(request.user),
    }
    context.update(chain.__dict__)
    return render(request, "wordchain_app/play.html", context)


@login_required
def about(request):
    return render(request, "wordchain_app/about.html", {"style": set_style(request.user)})


def sign_up(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('wordchain:play')
    else:
        form = UserForm()
    return render(request, "registration/sign_up.html", {'form': form})


@login_required
def update_account_details(request):
    if request.method == 'POST':
        form = UserForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('wordchain:play')
    else:
        form = UserForm(instance=request.user)
    return render(request, "wordchain_app/update_account_details.html", {'form': form, "style": set_style(request.user)})


@login_required
def account(request):
    user = request.user.username
    first_name = request.user.first_name
    last_name = request.user.last_name

    if not SetView.objects.filter(user=request.user).exists():
        display_name, created = Display.objects.get_or_create(display_id=1, accessibility="Normal", visual_mode="Dark")
        display = SetView.objects.create(user=request.user, display=display_name)
        font = display_name.accessibility
        mode = display_name.visual_mode
    else:
        display = SetView.objects.get(user=request.user)
        display_name = display.display
        font = display_name.accessibility
        mode = display_name.visual_mode

    if request.method == 'POST':
        if request.POST.get('font') == "Normal" or request.POST.get('font') == "Bigger":
            font = request.POST.get('font')

        if request.POST.get('mode') == "Light" or request.POST.get('mode') == "Dark":
            mode = request.POST.get('mode')

        display_view = SetView.objects.get(user=request.user)
        display_view.display = Display.objects.get(accessibility=font, visual_mode=mode)
        display_view.save()

    context = {
        "user": user,
        "first_name": first_name,
        "last_name": last_name,
        "font": font,
        "mode": mode,
        "style": set_style(request.user),
    }

    return render(request, "wordchain_app/account.html", context)


@login_required
def stats(request):
    user = request.user
    highest_score_level1 = get_highest_score(user, 1)
    highest_score_level2 = get_highest_score(user, 2)
    highest_score_level3 = get_highest_score(user, 3)

    average_score_level1 = get_average_score(user, 1)
    average_score_level2 = get_average_score(user, 2)
    average_score_level3 = get_average_score(user, 3)

    all_scores = get_all_scores(user)
    download = create_download(highest_score_level1, highest_score_level2, highest_score_level3, average_score_level1, average_score_level2, average_score_level3, all_scores)
    all_scores = json.dumps(all_scores)
    context = {
        "user": user,
        "highest_score_level1": highest_score_level1,
        "highest_score_level2": highest_score_level2,
        "highest_score_level3": highest_score_level3,
        "average_score_level1": average_score_level1,
        "average_score_level2": average_score_level2,
        "average_score_level3": average_score_level3,
        "all_scores": all_scores,
        "download": download,
        "style": set_style(request.user)
    }
    return render(request, "wordchain_app/stats.html", context)


def get_highest_score(user, level):
    try:
        user_id = user.id
        user_scores = ReceiveScore.objects.filter(user_id=user_id)
        user_score_ids = list(user_scores.values_list('score__score_id', flat=True))
        all_results = Results.objects.filter(score__score_id__in=user_score_ids)

        all_results_chains = list(all_results.values_list('chain__chain_id', flat=True))
        all_chains = IsAssignedTo.objects.filter(Q(chain__chain_id__in=all_results_chains) & Q(level__difficulty__exact=level))

        all_chain_ids = list(all_chains.values_list('chain__chain_id', flat=True))
        all_chain_ids_scores = Results.objects.filter(chain__chain_id__in=all_chain_ids)

        highest_score = all_chain_ids_scores.order_by('-score__value').first().score.value
    except:
        return 0
    return 0 if highest_score is None else highest_score


def get_average_score(user, level):
    try:
        user_id = user.id
        user_scores = ReceiveScore.objects.filter(user_id=user_id)
        user_score_ids = list(user_scores.values_list('score__score_id', flat=True))
        all_results = Results.objects.filter(score__score_id__in=user_score_ids)

        all_results_chains = list(all_results.values_list('chain__chain_id', flat=True))
        all_chains = IsAssignedTo.objects.filter(Q(chain__chain_id__in=all_results_chains) & Q(level__difficulty__exact=level))

        all_chain_ids = list(all_chains.values_list('chain__chain_id', flat=True))
        all_chain_ids_scores = Results.objects.filter(chain__chain_id__in=all_chain_ids)

        average_score = list(all_chain_ids_scores.values_list('score__value', flat=True))
        average_score = round(sum(average_score)/len(average_score), 2)
    except:
        return 0
    return 0 if average_score is None else average_score


def get_all_scores(user):
    user_id = user.id
    user_scores = ReceiveScore.objects.filter(user_id=user_id)
    if not user_scores:
        return []
    user_score_ids = list(user_scores.values_list('score__score_id', flat=True))
    all_results = Results.objects.filter(score__score_id__in=user_score_ids)
    all_scores = list(all_results.values_list('chain__first_word', 'chain__sixth_word', 'score__value'))
    return [] if all_scores is None else all_scores


def create_download(highest_score_level1, highest_score_level2, highest_score_level3, average_score_level1, average_score_level2, average_score_level3, all_scores):
    download = {}
    download['Highest Easy Chain Score'] = highest_score_level1
    download['Highest Medium Chain Score'] = highest_score_level2
    download['Highest Hard Chain Score'] = highest_score_level3
    download['Average Easy Chain Score'] = average_score_level1
    download['Average Medium Chain Score'] = average_score_level2
    download['Average Hard Chain Score'] = average_score_level3
    download['All Scores'] = []
    for score in all_scores:
        s = {}
        s['First Word'] = score[0]
        s['Sixth Word'] = score[1]
        s['Score'] = score[2]
        download['All Scores'].append(s)
    download = json.dumps(download)
    return download


def set_style(user):
    if not SetView.objects.filter(user=user).exists():
        display_name, created = Display.objects.get_or_create(display_id=1, accessibility="Normal", visual_mode="Dark")
        display = SetView.objects.create(user=user, display=display_name)
        font = display_name.accessibility
        mode = display_name.visual_mode
    else:
        display = SetView.objects.get(user=user)
        display_name = display.display
        font = display_name.accessibility
        mode = display_name.visual_mode

    if (mode == "Dark" and font == "Normal"):
        style = "#body { background-color: #121213; }#game { color: #ffffff; } label { color: #ffffff; }"
    elif (mode == "Light" and font == "Normal"):
        style = "#body { background-color: #ffffff; }#game { color: #000000; } label { color: #000000; }"
    elif (mode == "Dark" and font == "Bigger"):
        style = "#body { background-color: #121213; }#game { color: #ffffff; font-size: 40px; } label { color: #ffffff; } .navbar { font-size: 30px; } .button4 { font-size: 25px; height: 65px; }"
    else:
        style = "#body { background-color: #ffffff; }#game { color: #000000; font-size: 40px; } label { color: #000000; } .navbar { font-size: 30px; } .button4 { font-size: 25px; height: 65px; }"

    return style

wordchain_app/templates/wordchain_app/about.html
{% extends 'wordchain_app/base.html' %}
{% block content %}

<head>
	<title>Word Chain - About</title>
</head>
<div style="text-align-last:center;">
	<h3>How to play:</h3>
	<p>You will be guessinng a chain of six words that are connected by two word phrases (e.g. WIDE, OPEN, SESAME,
		STREET, CAR, ALARM).</p>
	<p>You are given the first and last word in the chain, and your goal is to then guess the four words that lead
		the first word to the last.</p>
	<p>You will start by getting the first letter of the second word in the chain,<br>then you must think of a word that
		connects to the first in a two word phrase (e.g. SPACE SHUTTLE, SHUTTLE BUS).</p>
	<p>If you guess correct, you will move to the next word until you reach the end.</p>
	<p>If you guess wrong, you will receive another letter in the word to help with your guesses.</p>
</div>
<a href="{% url 'wordchain:play' %}">
	<button class="button button4">Play</button>
</a>
{% endblock %}

wordchain_app/templates/wordchain_app/account.html
{% extends 'wordchain_app/base.html' %}
{% block content %}

<head>
	<title>Word Chain - Account</title>
</head>
<div style="text-align-last:center;">
	<h3>Account Details:</h3>
	<p>Name: {{ first_name }} {{ last_name }}</p>
	<p>Username: {{ user }}</p>
	<a href="{% url 'wordchain:update_account_details' %}">
		<button class="button button4">Update Account</button>
	</a>
	<h3>Display Settings: </h3>
	<p>Font Size: {{ font }}</p>
	<p>Mode: {{ mode }}</p>
	<button class="button button4" onclick="myFunction()">Change Display</button>
	<div id="myDIV" style="display: none;">
		<form method="post">
			{% csrf_token %}
			<p>Font Size: </p>
			<label style="display: inline-block">
				<input type="radio" id="normal" name="font" value="Normal">
				<span>Normal</span>
			</label>
			<label style="display: inline-block">
				<input type="radio" id="bigger" name="font" value="Bigger">
				<span>Bigger</span>
			</label>
			<p>Mode: </p>
			<label style="display: inline-block">
				<input type="radio" id="dark" name="mode" value="Dark">
				<span>Dark</span>
			</label>
			<label style="display: inline-block">
				<input type="radio" id="light" name="mode" value="Light">
				<span>Light</span>
			</label>
			</br>
			<input type="submit" value="Done" class="button button4" onclick="secondFunction()">
		</form>
	</div>
</div>
<script>
	function myFunction() {
		var x = document.getElementById("myDIV");
		if (x.style.display === "none") {
			x.style.display = "block";
		} else {
			x.style.display = "none";
		}
	}
	function secondFunction() {
		var x = document.getElementById("myDIV");
		x.style.display = "none";
	}
</script>
{% endblock %}

wordchain_app/templates/wordchain_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<link rel="stylesheet" type="text/css" href="{% static 'wordchain_app/style.css' %}">
	<style>
		{{ style }}
	</style>
</head>

<body id="body">
	<ul class="navbar">
		<li><a href="{% url 'wordchain:play' %}">Play</a></li>
		<li><a href="{% url 'wordchain:account' %}">Account</a></li>
		<li><a href="{% url 'wordchain:about' %}"> About</a></li>
		<li><a href="{% url 'wordchain:stats' %}">Stats</a></li>
		<li style="float:right"><a href="/accounts/logout/">Log Out</a></li>
	</ul>
	<div class="game-container" id="game">
		<div class="title-container">
			<h1>Word Chain</h1>
		</div>
		{% block content %}
		{% endblock %}
	</div>
</body>

</html>

wordchain_app/templates/wordchain_app/play-no-chains.html
{% extends 'wordchain_app/base.html' %}
{% block content %}
<div class="game-container" id="game">
	<h3>Wow! You've been busy!</h3>
	<p>Unfortunately there are no chains left for you to play right now!</p>
</div>
{% endblock %}

wordchain_app/templates/wordchain_app/play.html
{% extends 'wordchain_app/base.html' %}
{% load static %}
{% block content %}

<head>
	<title>Word Chain - Play</title>
</head>
<div class="game-container" id="game">
	<div class="score-container">
		<p id="score">Score: 0</p>
	</div>
	<div class="modal" id="game-modal">
		<div class="modal-content"></div>
	</div>
	<div class="tile-container"></div>
</div>
<div class="button-container">
	<button class="button4 clear-and-check" style="margin:10px;" name="clear" id="clear">Clear</button>
	<button class="button4 clear-and-check" style="margin:10px;" name="check" id="check">Check</button>
</div>
<p id="chain-id" hidden>{{ chain_id }}</p>
<p id="first-word" hidden>{{ first_word }}</p>
<p id="second-word" hidden>{{ second_word }}</p>
<p id="third-word" hidden>{{ third_word }}</p>
<p id="fourth-word" hidden>{{ fourth_word }}</p>
<p id="fifth-word" hidden>{{ fifth_word }}</p>
<p id="sixth-word" hidden>{{ sixth_word }}</p>
<p id="level" hidden>{{ level }}</p>
<script type="text/javascript" src="{% static 'wordchain_app/game.js' %}"></script>
{% endblock %}

wordchain_app/templates/wordchain_app/stats.html
{% extends 'wordchain_app/base.html' %}
{% load static %}
{% block content %}

<head>
	<title>Word Chain - Stats</title>
</head>
<div style="text-align-last:center;">
	<h3>{{ user }}'s stats</h3>
	<h4>Highest Easy Chain Score: {{ highest_score_level1 }}</h4>
	<h4>Average Easy Chain Score: {{ average_score_level1 }}</h4>
	<br>
	<h4>Highest Medium Chain Score: {{ highest_score_level2 }}</h4>
	<h4>Average Medium Chain Score: {{ average_score_level2 }}</h4>
	<br>
	<h4>Highest Hard Chain Score: {{ highest_score_level3 }}</h4>
	<h4>Average Hard Chain Score: {{ average_score_level3 }}</h4>
	<br>
	<h4>All Games So Far:</h4>
	<div class="completed-games"></div>
</div>
<br>
<div class="download-container">
	<p id="download-content" hidden>{{ download }}</p>
	<p id="all-scores" hidden>{{ all_scores }}</p>
	<button class="btn button4" id="download-button">Export My Stats</button>
</div>
<script id="all-game-stats-js" data-scores="{{ all_scores }}" type="text/javascript"
	src="{% static 'wordchain_app/stats.js' %}"></script>
{% endblock %}

wordchain_app/templates/wordchain_app/update_account_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'wordchain_app/style.css' %}">
</head>

<body>
	<div class="container rounded game-container">
		<h1 style="text-align: center;">Update your account details</h1>
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn button4">Update</button>
		</form>
	</div>
</body>

</html>